export const menus = [
  {
    restaurant: {
      id: 1,
      name: "Yeon JAE Food InC",
    },
    food_id: 1,
    user: {
      id: 1,
      name: "Yeon JAE",
    },
    rating: 4.12,
    food_name: "ramen",
    review: "asdf",
    price: "30.10",
    food_url: require("./src/assets/wafple_food_example.png"),
    created_at: "2022-01-01",
    updated_at: "2022-01-02",
  },
  {
    restaurant: {
      id: 2,
      name: "Hanabom",
    },
    food_id: 1,
    user: {
      id: 1,
      name: "Yeon JAE",
    },
    rating: 4.0,
    food_name: "Hana Pasta",
    review: "asdf",
    price: "30.10",
    food_url: require("./src/assets/wafple_food_example.png"),
    created_at: "2022-01-01",
    updated_at: "2022-01-02",
  },
  {
    restaurant: {
      id: 3,
      name: "Pizza Pizza",
    },
    food_id: 1,
    user: {
      id: 1,
      name: "Yeon JAE",
    },
    rating: 4.0,
    food_name: "Meat Lover",
    review: "asdf",
    price: "30.10",
    food_url: require("./src/assets/wafple_food_example.png"),
    created_at: "2022-01-01",
    updated_at: "2022-01-02",
  },
  {
    restaurant: {
      id: 4,
      name: "MOMO",
    },
    food_id: 1,
    user: {
      id: 1,
      name: "Yeon JAE",
    },
    rating: 4.0,
    food_name: "Sushi",
    review: "asdf",
    price: "30.10",
    food_url: require("./src/assets/wafple_food_example.png"),
    created_at: "2022-01-01",
    updated_at: "2022-01-02",
  },
  {
    restaurant: {
      id: 7,
      name: "Hansik",
    },
    food_id: 1,
    user: {
      id: 1,
      name: "Yeon JAE",
    },
    rating: 4.0,
    food_name: "Soondae Gukbap",
    review: "asdf",
    price: "30.10",
    food_url: require("./src/assets/wafple_food_example.png"),
    created_at: "2022-01-01",
    updated_at: "2022-01-02",
  },
  {
    restaurant: {
      id: 1,
      name: "Yeon JAE Food InC",
    },
    food_id: 1,
    user: {
      id: 1,
      name: "Yeon JAE",
    },
    rating: 4.0,
    food_name: "Recommended",
    review: "asdf",
    price: "30.10",
    food_url: require("./src/assets/wafple_food_example.png"),
    created_at: "2022-01-01",
    updated_at: "2022-01-02",
  },
  {
    restaurant: {
      id: 1,
      name: "Yeon JAE Food InC",
    },
    food_id: 1,
    user: {
      id: 1,
      name: "Yeon JAE",
    },
    rating: 4.0,
    food_name: "Recommended",
    review: "asdf",
    price: "30.10",
    food_url: require("./src/assets/wafple_food_example.png"),
    created_at: "2022-01-01",
    updated_at: "2022-01-02",
  },
  {
    restaurant: {
      id: 1,
      name: "Yeon JAE Food InC",
    },
    food_id: 1,
    user: {
      id: 1,
      name: "Yeon JAE",
    },
    rating: 4.0,
    food_name: "Recommended",
    review: "asdf",
    price: "30.10",
    food_url: require("./src/assets/wafple_food_example.png"),
    created_at: "2022-01-01",
    updated_at: "2022-01-02",
  },
  {
    restaurant: {
      id: 1,
      name: "Yeon JAE Food InC",
    },
    food_id: 1,
    user: {
      id: 1,
      name: "Yeon JAE",
    },
    rating: 4.0,
    food_name: "Recommended",
    review: "asdf",
    price: "30.10",
    food_url: require("./src/assets/wafple_food_example.png"),
    created_at: "2022-01-01",
    updated_at: "2022-01-02",
  },
  {
    restaurant: {
      id: 1,
      name: "Yeon JAE Food InC",
    },
    food_id: 1,
    user: {
      id: 1,
      name: "Yeon JAE",
    },
    rating: 4.0,
    food_name: "Recommended",
    review: "asdf",
    price: "30.10",
    food_url: require("./src/assets/wafple_food_example.png"),
    created_at: "2022-01-01",
    updated_at: "2022-01-02",
  },
  {
    restaurant: {
      id: 1,
      name: "Yeon JAE Food InC",
    },
    food_id: 1,
    user: {
      id: 1,
      name: "Yeon JAE",
    },
    rating: 4.0,
    food_name: "Recommended",
    review: "asdf",
    price: "30.10",
    food_url: require("./src/assets/wafple_food_example.png"),
    created_at: "2022-01-01",
    updated_at: "2022-01-02",
  },
  {
    restaurant: {
      id: 1,
      name: "Yeon JAE Food InC",
    },
    food_id: 1,
    user: {
      id: 1,
      name: "Yeon JAE",
    },
    rating: 4.0,
    food_name: "Recommended",
    review: "asdf",
    price: "30.10",
    food_url: require("./src/assets/wafple_food_example.png"),
    created_at: "2022-01-01",
    updated_at: "2022-01-02",
  },
  {
    restaurant: {
      id: 1,
      name: "Yeon JAE Food InC",
    },
    food_id: 1,
    user: {
      id: 1,
      name: "Yeon JAE",
    },
    rating: 4.0,
    food_name: "Recommended",
    review: "asdf",
    price: "30.10",
    food_url: require("./src/assets/wafple_food_example.png"),
    created_at: "2022-01-01",
    updated_at: "2022-01-02",
  },
  {
    restaurant: {
      id: 1,
      name: "Yeon JAE Food InC",
    },
    food_id: 1,
    user: {
      id: 1,
      name: "Yeon JAE",
    },
    rating: 4.0,
    food_name: "Recommended",
    review: "asdf",
    price: "30.10",
    food_url: require("./src/assets/wafple_food_example.png"),
    created_at: "2022-01-01",
    updated_at: "2022-01-02",
  },
  {
    restaurant: {
      id: 1,
      name: "Yeon JAE Food InC",
    },
    food_id: 1,
    user: {
      id: 1,
      name: "Yeon JAE",
    },
    rating: 4.0,
    food_name: "Recommended",
    review: "asdf",
    price: "30.10",
    food_url: require("./src/assets/wafple_food_example.png"),
    created_at: "2022-01-01",
    updated_at: "2022-01-02",
  },
  {
    restaurant: {
      id: 1,
      name: "Yeon JAE Food InC",
    },
    food_id: 1,
    user: {
      id: 1,
      name: "Yeon JAE",
    },
    rating: 4.0,
    food_name: "Recommended",
    review: "asdf",
    price: "30.10",
    food_url: require("./src/assets/wafple_food_example.png"),
    created_at: "2022-01-01",
    updated_at: "2022-01-02",
  },
  {
    restaurant: {
      id: 1,
      name: "Yeon JAE Food InC",
    },
    food_id: 1,
    user: {
      id: 1,
      name: "Yeon JAE",
    },
    rating: 4.0,
    food_name: "Recommended",
    review: "asdf",
    price: "30.10",
    food_url: require("./src/assets/wafple_food_example.png"),
    created_at: "2022-01-01",
    updated_at: "2022-01-02",
  },
  {
    restaurant: {
      id: 1,
      name: "Yeon JAE Food InC",
    },
    food_id: 1,
    user: {
      id: 1,
      name: "Yeon JAE",
    },
    rating: 4.0,
    food_name: "Recommended",
    review: "asdf",
    price: "30.10",
    food_url: require("./src/assets/wafple_food_example.png"),
    created_at: "2022-01-01",
    updated_at: "2022-01-02",
  },
  {
    restaurant: {
      id: 1,
      name: "Yeon JAE Food InC",
    },
    food_id: 1,
    user: {
      id: 1,
      name: "Yeon JAE",
    },
    rating: 4.0,
    food_name: "Recommended",
    review: "asdf",
    price: "30.10",
    food_url: require("./src/assets/wafple_food_example.png"),
    created_at: "2022-01-01",
    updated_at: "2022-01-02",
  },
];
